### PR TITLE
changed logo folder to lowercase

### PR DESCRIPTION
**Pull request by Debiday**
Changing logo folder name from uppercase to lowercase for consistency and to avoid case-sensitive issues.

### CODE REVIEW

**Comment by stackedsax** [comment]
@c-rindi can you think of any place where these logos might be being used in the real world?  I looked through the code in the repo and nothing seems to refer to these assets directly, so I think this is safe to do.  Just thought I'd check with you first.

**Comment by c-rindi** [comment]
@stackedsax Good call - I don't think they're being used yet, so we should be safe to do this now.

This folder renaming is a correction of mistake in naming the folder originally.

**Review by stackedsax — APPROVED** [review]
lgtm. 👍

**Comment by stackedsax** [comment]
eh, I just realized these weren't in the `docs` folder.  I think it might be good to move them there instead and keep the root folder a little cleaner.  @Debiday could you submit another PR for that (or revert this one and fix, if you prefer, but maybe just cleaner to submit a new one).

**Comment by Debiday** [comment]
Got it, made a new PR here to move to the docs folder [here](https://github.com/G-Research/thanos-remote-read/pull/24)

**Comment by Debiday** [comment]
Thank you @stackedsax!

**Pull request merged**
